AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Layout/LineLength:
  Max: 120

Layout/MethodLength:
  Max: 20
