module RbsDiscard
  module Discard
    def self.all: () -> Array[singleton(Discard::Model)]
    def self.class_to_rbs: (singleton(Discard::Model) klass) -> String

    class Generator
      attr_reader klass: singleton(Discard::Model)
      attr_reader klass_name: String

      def initialize: (singleton(Discard::Model) klass) -> void
      def generate: () -> String

      private

      def klass_decl: () -> String
      def header: () -> String
      def footer: () -> String
    end
  end
end
